# Generated by Django 2.2.5 on 2019-09-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_profile_img', upload_to='images/profiles'),
        ),
    ]
