# Generated by Django 2.2.5 on 2019-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images/projects/NO_IMAGE.png', null=True, upload_to='images/projects'),
        ),
    ]
