# Generated by Django 2.2.5 on 2019-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_members_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images/projects/no_img.webp', null=True, upload_to='images/projects'),
        ),
    ]
