# Generated by Django 2.2.5 on 2019-09-07 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.TextField(blank=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
