# Generated by Django 2.2.5 on 2020-01-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20190909_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
