# Generated by Django 2.2.5 on 2019-09-07 17:28

import django.contrib.postgres.fields
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='EUR', max_digits=14), size=None),
        ),
    ]
